"""add refresh token hash

Revision ID: 52f889c5f056
Revises: bbd2ed860a00
Create Date: 2026-07-30 05:42:44.317762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52f889c5f056'
down_revision: Union[str, Sequence[str], None] = 'bbd2ed860a00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_users', sa.Column('refresh_token_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_users', 'refresh_token_hash')
    # ### end Alembic commands ###
