"""create medals and user_medals tables

Revision ID: 67ad2af7c632
Revises: 1fcb3cf823b2
Create Date: 2026-07-31 06:28:22.284303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67ad2af7c632'
down_revision: Union[str, Sequence[str], None] = '1fcb3cf823b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=254), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('rarity', sa.Enum('BRONZE', 'SILVER', 'GOLD', name='medalrarity'), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medals_code'), 'medals', ['code'], unique=True)
    op.create_index(op.f('ix_medals_id'), 'medals', ['id'], unique=False)
    op.create_table('user_medals',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('medal_id', sa.Integer(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medal_id'], ['medals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['api_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'medal_id')
    )
    # ### end Alembic commands ###
    
    # Seed default medals
    op.bulk_insert(
        sa.table(
            "medals",
            sa.column("code", sa.String),
            sa.column("name", sa.String),
            sa.column("description", sa.String),
            sa.column("rarity", sa.String),
            sa.column("points", sa.Integer),
        ),
        [
            {
                "code": "FIRST_LOGIN",
                "name": "Première visite",
                "description": "Bienvenue dans Harmony",
                "rarity": "BRONZE",
                "points": 5,
            },
            {
                "code": "FIRST_STEPS",
                "name": "Premiers pas",
                "description": "Commencer à bouger",
                "rarity": "BRONZE",
                "points": 10,
            },
            {
                "code": "TEN_K_STEPS",
                "name": "10K Club",
                "description": "Une grosse journée",
                "rarity": "BRONZE",
                "points": 20,
                "icon": "walk"
            },
            {
                "code": "ONE_HUNDRED_K_TOTAL",
                "name": "Explorateur",
                "description": "Vous allez loin",
                "rarity": "SILVER",
                "points": 50,
                "icon": "walk"
            },
            {
                "code": "THREE_DAY_STREAK",
                "name": "Série naissante",
                "description": "Se connecter plusieurs jours d’affilée",
                "rarity": "BRONZE",
                "points": 25,
            },
        ]
    )
    # End seed


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_medals')
    op.drop_index(op.f('ix_medals_id'), table_name='medals')
    op.drop_index(op.f('ix_medals_code'), table_name='medals')
    op.drop_table('medals')
    # ### end Alembic commands ###