"""enhanced users table

Revision ID: bbd2ed860a00
Revises: 18c401e1f852
Create Date: 2026-07-29 15:24:36.747106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bbd2ed860a00'
down_revision: Union[str, Sequence[str], None] = '18c401e1f852'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_users', sa.Column('public_id', sa.String(length=36), nullable=False))
    op.add_column('api_users', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.add_column('api_users', sa.Column('display_name', sa.String(length=50), nullable=False))
    op.add_column('api_users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.add_column('api_users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('api_users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=254),
               existing_nullable=False)
    op.create_index(op.f('ix_api_users_display_name'), 'api_users', ['display_name'], unique=True)
    op.create_index(op.f('ix_api_users_public_id'), 'api_users', ['public_id'], unique=True)
    op.drop_column('api_users', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_users', sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=False))
    op.drop_index(op.f('ix_api_users_public_id'), table_name='api_users')
    op.drop_index(op.f('ix_api_users_display_name'), table_name='api_users')
    op.alter_column('api_users', 'email',
               existing_type=sa.String(length=254),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('api_users', 'last_login')
    op.drop_column('api_users', 'is_verified')
    op.drop_column('api_users', 'display_name')
    op.drop_column('api_users', 'hashed_password')
    op.drop_column('api_users', 'public_id')
    # ### end Alembic commands ###
